[project]
name = "voxcraft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Balasubramanian Duraiswamy", email = "dbala2007@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "kokoro==0.9.4",
    "misaki[en]>=0.9.4",
    "soundfile>=0.14.0",
    "streamlit>=1.65.0",
    "torchvision>=0.29.1",
    "transformers>=4.46",
]

[project.scripts]
voxcraft = "voxcraft.main:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
